services:
  postgres-matchmaker-api:
    image: postgres:17.4-alpine
    container_name: postgres-matchmaker-api
    ports:
      - 5432:5432
    volumes:
      - matchmaker-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-matchmaker-api

  postgres-identity-service:
    image: postgres:17.4-alpine
    container_name: postgres-identity
    ports:
      - 5433:5432
    volumes:
      - identity-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-identity-service

  sqnc-identity-service:
    image: digicatapult/sqnc-identity-service:latest
    container_name: identity-service
    command: /bin/sh -c "
      sleep 30 &&
      npm run db:migrate &&
      npm start"
    ports:
      - 3002:3000
    environment:
      - API_HOST=sqnc-node
      - DB_HOST=postgres-identity-service
      - DB_PORT=5432
      - DB_NAME=sqnc-identity-service
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SELF_ADDRESS=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - IDP_CLIENT_ID=sequence
      - IDP_PUBLIC_URL_PREFIX=http://localhost:3080/realms/member-a/protocol/openid-connect
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/member-a/protocol/openid-connect

  sqnc-node:
    image: digicatapult/sqnc-node:latest
    container_name: node
    command: --base-path /data/
      --dev
      --unsafe-rpc-external
      --rpc-max-connections 512
      --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure

  ipfs:
    image: ipfs/go-ipfs:v0.33.2
    container_name: ipfs
    environment:
      - IPFS_LOGGING=info
      - IPFS_TRACING=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_SERVICE_NAME=ipfs
      - GRPC_INSECURE=true
      - |
        IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/
        /base16/
        0000000000000000000000000000000000000000000000000000000000000000
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_TRACING_ENABLED=true
      - KC_TRACING_ENDPOINT=http://jaeger:4317
      - OTEL_PROPAGATORS=tracecontext,baggage
    ports:
      - 3080:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 4318:4318
      - 4317:4317
      - 6831:6831/udp
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 5778:5778
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    scale: 0

volumes:
  matchmaker-api-storage:
  identity-storage:
